### ISSUE TITLE
Underscore seems to break resource group naming regex

### ISSUE THREAD

**Issue by invisibleninja06** [gsoft-inc/terraform-azurerm-naming#4]
Underscore is a valid character for resource groups

The following fails
RG-TST-DEV-Main_NodePool-j4536dd634745qk
RG_TST_DEV_Main_NodePool-j4536dd634745qk

`^[a-zA-Z0-9]{1}[a-zA-Z0-9-]*$` should thus become `^[a-zA-Z0-9]{1}[a-zA-Z0-9-_]*$`

**Comment by yohanb** [comment]
Fixed! Thanks for the issue.
