### ISSUE TITLE
Add help section to override suffix and separator

### ISSUE THREAD

**Issue by invisibleninja06** [gsoft-inc/terraform-azurerm-naming#5]
It unclear to me how to override the random suffix generation as well as how to change the separator used.

In my case for storage accounts I rather not have 0 as separator, in fact id like no separator at all.
The following does not work 

```tf
module "csazname_storage_account" {
  source    = "gsoft-inc/naming/azurerm//modules/storage/storage_account"
  name      = lower(var.rg_rs_basename)
  prefixes  = ["st", lower(var.rg_project), lower(var.rg_projecttype)]
  separator = ""
}
```

This results in `An argument named "separator" is not expected here.`

Setting the suffixes to `[]` results in regular generation, since its the default.
Setting the suffixes to `null` results in error
setting suffixes to `[""]` result in no suffix but a separator is still present

Appreciate any assistance

**Comment by yohanb** [comment]
Hey @invisibleninja06.  I know I'm late to the party but I wanted to let you know I've made the changes to the modules in order to support an empty string separator and also empty array suffix.
Cheers!

**Comment by invisibleninja06** [comment]
Much appreciated!
